#!/bin/bash
#
# process-powermetrics-output.sh
#
# Script to postprocess macOS powermetrics output that gets send via Netcat to this 
# Linux host. The purpose is to provide input files for RPi-Monitor to nicely graph
# power management and performance data from Intel and "Apple Silicon" macs. A yet
# not finished Check_MK agent plugin will also postprocess the output generated by
# this script.
#
# Prerequisits:
#
# on this host (netcat receiver):
# nc -l 9999 >/tmp/powermetrics-mbp16-tk.log
#
# on the mac (netcat sender):
# powermetrics -s smc,cpu_power,gpu_power 2>/dev/null | egrep --line-buffered "^Intel energy model|^System Average fr|^Package 0 C-st|^CPU/GPU Over|^Cores Active|^GPU Active|^Avg Num of|^CPU Thermal l|^GPU Thermal l|^IO Thermal l|^Fan:|^CPU die t|^GPU die t|^CPU Pl|^GPU Pl|^Number of pr" | nc nagios 9999
#
# If you want to monitor more than one machine you need foe each Mac a different port 
# and a different log file and also an additional line in the while loop below.
#
# The output will look like this on an Intel machine:
#
# Intel energy model derived package power (CPUs+GT+SA): 1.07W
# System Average frequency as fraction of nominal: 59.63% (1550.27 Mhz)
# Package 0 C-state residency: 76.12% (C2: 8.66% C3: 0.14% C6: 1.89% C7: 12.72% C8: 52.72% C9: 0.00% C10: 0.00% )
# CPU/GPU Overlap: 0.20%
# Cores Active: 21.10%
# GPU Active: 0.44%
# Avg Num of Cores Active: 0.31
# CPU Thermal level: 0
# GPU Thermal level: 0
# IO Thermal level: 0
# Fan: 1823.21 rpm
# CPU die temperature: 36.80 C
# GPU die temperature: 35.00 C
# CPU Plimit: 0.00
# GPU Plimit (Int): 0.00 
# Number of prochots: 0

export PATH=/usr/sbin:/usr/bin:/sbin:/bin

TmpFile=$(mktemp /tmp/${0##*/}.XXXXXX)
trap "rm \"${TmpFile}\" ; exit 0" 0 1 2 3 15

CheckMachine() {
	Machine=$1
	MachineDir=/tmp/rpimonitor/${Machine}
	[ -d ${MachineDir} ] || mkdir -p -m2777 ${MachineDir}
	Logfile=/tmp/powermetrics-${Machine}.log
	tail -n 31 ${Logfile} >${TmpFile}
	
	grep "^Intel energy model" ${TmpFile} | tail -n1 | cut -f2 -d':' | tr -d -c '[:digit:]' >${MachineDir}/power
	grep "^System Average fr" ${TmpFile} | tail -n1 | awk -F" " '{print $9}' | sed 's/(//' >${MachineDir}/avg_frequency
	grep "^Package 0 C-st" ${TmpFile} | tail -n1 | awk -F" " '{print $5}' | sed 's/%//' >${MachineDir}/c_state_residency
	grep "^CPU/GPU Over" ${TmpFile} | tail -n1 | awk -F" " '{print $3}' | sed 's/%//' >${MachineDir}/cpu_gpu_overlap
	grep "^Cores Active" ${TmpFile} | tail -n1 | awk -F" " '{print $3}' | sed 's/%//' >${MachineDir}/cores_active
	grep "^GPU Active" ${TmpFile} | tail -n1 | awk -F" " '{print $3}' | sed 's/%//' >${MachineDir}/gpu_active
	grep "^Avg Num of" ${TmpFile} | tail -n1 | awk -F" " '{print $6}' >${MachineDir}/avg_num_cores_active
	grep "^CPU Thermal l" ${TmpFile} | tail -n1 | awk -F" " '{print $4}' >${MachineDir}/cpu_thermal_level
	grep "^GPU Thermal l" ${TmpFile} | tail -n1 | awk -F" " '{print $4}' >${MachineDir}/gpu_thermal_level
	grep "^IO Thermal l" ${TmpFile} | tail -n1 | awk -F" " '{print $4}' >${MachineDir}/io_thermal_level
	grep "^Fan:" ${TmpFile} | tail -n1 | awk -F" " '{print $2}' >${MachineDir}/fan_rpm
	grep "^CPU die t" ${TmpFile} | tail -n1 | awk -F" " '{print $4}' >${MachineDir}/cpu_die_temp
	grep "^GPU die t" ${TmpFile} | tail -n1 | awk -F" " '{print $4}' >${MachineDir}/gpu_die_temp
	grep "^CPU Pl" ${TmpFile} | tail -n1 | awk -F" " '{print $3}' >${MachineDir}/cpu_plimit
	grep "^GPU Pl" ${TmpFile} | tail -n1 | awk -F" " '{print $4}' >${MachineDir}/gpu_plimit
	grep "^Number of pr" ${TmpFile} | tail -n1 | awk -F" " '{print $4}' >${MachineDir}/prochots
} # CheckMachine

while true ; do
	CheckMachine mbp16-tk
	# CheckMachine mbair
	# CheckMachine mbp13-yb
	sleep 2
done