#!/bin/bash
#
# Monitor zswap usage on Linux. Takes the raw values from sysfs and
# feeds them as graphs into Check_MK.
#
# root@athene:/sys/kernel/debug# grep -R . zswap/
# zswap/same_filled_pages:0
# zswap/stored_pages:0
# zswap/pool_total_size:0
# zswap/duplicate_entry:0
# zswap/written_back_pages:0
# zswap/reject_compress_poor:0
# zswap/reject_kmemcache_fail:0
# zswap/reject_alloc_fail:0
# zswap/reject_reclaim_fail:0
# zswap/pool_limit_hit:0
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

export PATH=/usr/sbin:/usr/bin:/sbin:/bin

if [ ! -d /sys/kernel/debug/zswap ]; then
	echo -e "<<<mrpe>>>\n(${0##*/}) Zswap 3 UNKN - /sys/kernel/debug/zswap not accessible, no zswap data available"
	exit
fi

ZswapGraph="$(grep -R . /sys/kernel/debug/zswap/ | while read ; do sed 's/:/=/' <<< ${REPLY##*/} ; done | tr "\n" " ")"
ZswapStatus="$(dmesg | awk -F": " '/zswap: / {print $2}')"
case ${ZswapStatus} in
	*"loaded using"*)
		CheckState="0 OK"
		;;
	*)
		CheckState="1 WARN"
		;;
esac
echo -e "<<<mrpe>>>\n(${0##*/}) Zswap ${CheckState} - ${ZswapStatus} | ${ZswapGraph}"