#!/bin/bash
#
# Monitor zswap usage on Linux. Takes the raw values from sysfs and
# feeds them as graphs into Check_MK.
#
# root@athene:/sys/kernel/debug# grep -R . zswap/
# zswap/same_filled_pages:0
# zswap/stored_pages:0
# zswap/pool_total_size:0
# zswap/duplicate_entry:0
# zswap/written_back_pages:0
# zswap/reject_compress_poor:0
# zswap/reject_kmemcache_fail:0
# zswap/reject_alloc_fail:0
# zswap/reject_reclaim_fail:0
# zswap/pool_limit_hit:0
#
# Only exception: pool_total_size will be converted to MB and sent
# as pool_total_size_mb.
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

export PATH=/usr/sbin:/usr/bin:/sbin:/bin

if [ ! -d /sys/kernel/debug/zswap ]; then
	echo -e "<<<mrpe>>>\n(${0##*/}) Zswap 3 UNKN - /sys/kernel/debug/zswap not accessible, no zswap stats available"
	exit
fi

ZswapStats="$(grep -R . /sys/kernel/debug/zswap/ | while read ; do sed 's/:/=/' <<< ${REPLY##*/} ; done | tr "\n" " ")"
eval ${ZswapStats}
if [ ${pool_total_size} -gt 0 ]; then
	# https://unix.stackexchange.com/a/412760
	compression_ratio=$(bc -l <<< "${stored_pages} * 4096 / ${pool_total_size}")
fi
total_size_mb=$(bc -l <<<"${pool_total_size} / 1048576")

read max_pool_percent </sys/module/zswap/parameters/max_pool_percent 2>/dev/null
read compressor </sys/module/zswap/parameters/compressor 2>/dev/null
read zpool </sys/module/zswap/parameters/zpool 2>/dev/null

if [ ${pool_limit_hit} -eq 0 ]; then
	CheckState="0 OK"
	ZswapStatus="Using ${compressor}/${zpool}, $(cut -d'.' -f1 <<<${total_size_mb}) MB used"
else
	CheckState="1 WARN"
	ZswapStatus="Using ${compressor}/${zpool}, $(cut -d'.' -f1 <<<${total_size_mb}) MB used, ${pool_limit_hit} pool limit hits"
fi
echo -e "<<<mrpe>>>\n(${0##*/}) Zswap ${CheckState} - ${ZswapStatus} | same_filled_pages=${same_filled_pages} stored_pages=${stored_pages} pool_total_size_mb=${total_size_mb} duplicate_entry=${duplicate_entry} written_back_pages=${written_back_pages} reject_compress_poor=${reject_compress_poor} reject_kmemcache_fail=${reject_kmemcache_fail} reject_alloc_fail=${reject_alloc_fail} reject_reclaim_fail=${reject_reclaim_fail} pool_limit_hit=${pool_limit_hit} compression_ratio=${compression_ratio} max_pool_percent=${max_pool_percent}"